spring:
  application:
    name: spring-reactive-r2dbc
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url:  r2dbc:mysql://localhost:3306/medsdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: password
    nitialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1