spring:
  application:
    name: spring-reactive-r2dbc
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url:  r2dbc:mysql://localhost:3306/medsdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: password
    nitialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1




#  spring.datasource.url: jdbc:mysql://localhost:3306/medsdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#  spring.datasource.username: root
#  spring.datasource.password: password
#  spring.datasource.driverClassName: com.mysql.jdbc.Driver
#  spring.jpa.hibernate.ddl-auto: create-drop
#
#  spring.jpa.properties.hibernate.dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
#  hibernate.show_sql: true
#  hibernate.hbm2ddl.auto: update
